---
- hosts: localhost
  gather_facts: no

  roles:
    - { role: host-variable-shared } # role::host-variable-shared


- hosts: hana
  serial: 2
  remote_user: root
  gather_facts: no

  vars:

          # Automate OS Installation
          # If ILO Can access to deployment server via using http protocol
          # You can enable this feature (true/false)
          automate_install: true
          installation_media: SLE-15-SP2-SAP-x86_64_Custom-DVD.iso

          # HANA Operating System Firewall / ture Or false
          firewall: true

          # Sap Servers Hostname / IP Informations
          fqdn: test.dom

          # Mail Relay Host / Admin Mail Address
          relayhost: XXX.XXX.XXX.XXX
          recipientmail: emre.baykal@hpe.com
          sendermail: test@hpe.com

          # Remote Sys Log Server
          rsys_log_srv: XXX.XXX.XXX.XXX
          rsys_log_srv_port: 514

          # Time Sync Parameters
          ntp_servers:
               hostname: XXX.XXX.XXX.XXX
               #hostname: 1.rhel.pool.ntp.org

          # HPE Oneview Config Parameters
          oneview_ip: XXX.XXX.XXX.XXX
          oneview_username: administrator
          oneview_password: xxxxxxxxxxxx
          email_sender: server@test.dom


          # Hana Installation files
          hana_deployment:
              server: IMDB_SERVER20_055_0-80002031.SAR
              client: IMDB_CLIENT20_008_16-80002082.SAR
              sapcar: SAPCAR_1324-80000935.EXE
              hostagent: saphostagentrpm_51-20009394.rpm
              spp: P26228_001_spp-2019.12.0-SPP2019120.2019_1209.4.iso
              source: /home/hpe/ansible/ansible-sap-hana-deploy/setup/html/media
              destination: /setup


  roles:
          - { role: proliant-server-preconfigure-shared }  # role::physical-server-preconfigure-shared
          - { role: sap-hana-preconfigure-shared }         # role::sap-hana-preconfigure-shared
          - { role: sap-hana-security-hardening }          # role::sap-hana-security-hardening
          - { role: sap-hana-deploy }                      # role::sap-hana-deploy
          - { role: sap-hana-replication }                 # role::sap-hana-replication
          - { role: oneview-config }                       # role::oneview-config
