---
- name: Configuring System Parameters
  template:
    src=files/boot-local
    dest=/etc/init.d/boot.local
    owner=root
    group=root
    mode=0644
    backup=yes

- name: Enable tuned service
  command: "{{item}}"
  with_items:
  - systemctl start tuned
  - systemctl enable tuned

- name: Enable Saptune Solution HANA
  command: "saptune solution apply HANA"

- name: Start Saptune Daemon
  command: "saptune daemon start"

- name: Aplly Vmware Sap Note
  command: "saptune note apply 2161991"
  when:
    - ansible_virtualization_type == "VMware"

- name: Configure Sysctl Parameters
  sysctl:
    name="{{ item.pname }}"
    value="{{ item.value }}"
    sysctl_set=yes
    state=present
    reload=yes
  with_items:
  - { pname: 'net.core.somaxconn', value: '4096'}
  - { pname: 'net.ipv4.tcp_max_syn_backlog', value: '8192'}
  - { pname: 'net.ipv4.tcp_tw_reuse', value: '1'}
  - { pname: 'net.ipv4.tcp_timestamps', value: '1'}
  - { pname: 'net.ipv4.tcp_window_scaling', value: '1'}
  - { pname: 'net.ipv4.tcp_slow_start_after_idle', value: '0'}
  - { pname: 'net.ipv4.ip_local_port_range', value: '40000 65300'}
  - { pname: 'net.ipv4.tcp_wmem', value: '4096 16384 4194304'}
  - { pname: 'net.ipv4.tcp_rmem', value: '4096 16384 4194304'}
  - { pname: 'net.core.rmem_max', value: '4194304'}
  - { pname: 'net.core.wmem_max', value: '4194304'}
  - { pname: 'net.ipv4.tcp_slow_start_after_idle', value: '0'}

- name: Create logint directory
  file:
    path: /etc/systemd/logind.conf.d
    state: directory
    mode: 0755

- name: UserTasksMax setting for user root
  copy:
    content: |
               [Login]
               UserTasksMax=infinity
    dest: /etc/systemd/logind.conf.d/sap-hana.conf
    mode: 0755

- name: Change grub File Parameters in to /etc/default/grub
  lineinfile:
      path=/etc/default/grub
      regexp="^GRUB_CMDLINE_LINUX_DEFAULT="
      line='GRUB_CMDLINE_LINUX_DEFAULT="splash={{ ansible_cmdline['splash'] }}  resume={{ ansible_cmdline['resume'] }}  mitigations={{ ansible_cmdline['mitigations'] }} quiet transparent_hugepage=never numa_balancing=disable intel_idle.max_cstate=1 processor.max_cstate=1 "'
  register: grub

- name: Run the grub2-mkconfig -o /boot/grub2/grub.cfg command to generate the grub configuration file
  command: "grub2-mkconfig -o /boot/grub2/grub.cfg"
  when: grub.changed

- name: Disabling the fstrim.timer and fstrim.service Services
  service:
    name="{{ item.sname }}"
    state="{{ item.state }}"
    enabled="{{ item.mode }}"
  with_items:
    - { sname: 'fstrim.timer', state: 'stopped', mode: 'no'}
    - { sname: 'fstrim.service', state: 'stopped', mode: 'no'}

- name: Rebooting ...
  shell: sleep 2 && /sbin/shutdown -r now "Reboot required for grub"
  async: 1
  poll: 0
  ignore_errors: true
  when: grub.changed
  register: rebooting

- name: Wait for system to become reachable
  wait_for_connection:
    timeout: 900
    sleep: 15
    delay: 30
  when: rebooting.changed
