---
- name: Sleep for 300 seconds and continue with play
  wait_for:
    timeout: 300
  delegate_to: localhost

- name: ILO REST Persistent Memory Config
  uri:
      url: "https://{{ server_hardware_ilo_ip }}/redfish/v1/Systems/1/bios/settings/"
      method: POST
      return_content: yes
      body: "{\"Attributes\": {\"MemoryControllerInterleaving\": \"Auto\",\"MaxMemBusFreqMHz\": \"Auto\" , \"MemPatrolScrubbing\": \"Enabled\", \"MemoryRemap\": \"NoAction\", \"PersistentMemAddressRangeScrub\": \"Enabled\", \"PersistentMemoryInterleaving\": \"Enabled\", \"SecurityFreezeLock\": \"Disabled\", \"ApplyDefaultNamespaces\": \"Disabled\" }}"
      body_format: json
      validate_certs: no
      user: "{{ server_hardware_username }}"
      password: "{{ server_hardware_password }}"
      force_basic_auth: yes
      status_code: 200
  delegate_to: localhost

- name: ILO REST POST Rebbot Server
  uri:
    url: "https://{{ server_hardware_ilo_ip }}/redfish/v1/Systems/1/Actions/ComputerSystem.Reset"
    method: POST
    return_content: yes
    body: "{\"ResetType\": \"ForceRestart\"}"
    body_format: json
    validate_certs: no
    user: "{{ server_hardware_username }}"
    password: "{{ server_hardware_password }}"
    force_basic_auth: yes
    status_code: 200
  delegate_to: localhost
