---

   - name: Install SUSE security checker
     zypper:
       name: "{{ item }}"
       state: present
     with_items:
      - seccheck
      - yast2-mail

   - name: Enable Monthy Seccheck Reports Service
     systemd:
       name: seccheck-monthly.timer
       state: started
       enabled: yes

   - name: Enable Automatic Logout Reports Service
     systemd:
       name: seccheck-autologout.timer
       state: started
       enabled: yes
