---

   - name: Change auditd.conf  Parameters in to /etc/audit/auditd.conf
     replace:
         path=/etc/audit/auditd.conf
         regexp="^{{ item.pname }}"
         replace="{{ item.value }}"
     with_items:
      - { pname: '^log_file\s=\s(.+)$', value: 'log_file = /var/log/audit/audit.log'}
      - { pname: '^max_log_file\s=\s(.+)$', value: 'max_log_file = 100'}
      - { pname: '^space_left\s=\s(.+)$', value: 'space_left = 400'}
      - { pname: '^admin_space_left\s=\s(.+)$', value: 'admin_space_left = 100'}
      - { pname: '^space_left_action\s=\s(.+)$', value: 'space_left_action = email'}
      - { pname: '^action_mail_acct\s=\s(.+)$', value: 'action_mail_acct = root'}
      - { pname: '^admin_space_left_action\s=\s(.+)$', value: 'admin_space_left_action = halt'}
     notify: restart_auditd_service

   - name: Force auditd services
     meta: flush_handlers

   - name: deploy auditd.rules file to the clients
     template:
       src: audit.j2
       dest: /etc/audit/rules.d/audit.rules
       owner: root
       group: root
       mode: 0640
       backup: yes
     notify: restart_auditd_service

   - name: Force auditd services
     meta: flush_handlers
