---

   - name: Set rsyslog Parameters in to /etc/rsyslog.d/remote.conf
     blockinfile:
        path: /etc/rsyslog.d/remote.conf
        marker: "## {mark} added by ansible (configuration rsyslog)"
        content: |
            $ModLoad imfile
            $InputFileName /var/log/audit/audit.log
            $InputFileTag tag_audit_log:
            $InputFileStateFile audit_log
            $InputFileSeverity info
            $InputFileFacility local6
            $InputRunFileMonitor
            $template TimeFormat,"%timereported% %HOSTNAME% %syslogtag%%msg%\n"
            $ActionFileDefaultTemplate TimeFormat

            *.notice;auth.info;authpriv.info;auth.info;local6.*        @@{{ rsys_log_srv }}:{{ rsys_log_srv_port }};TimeFormat
     notify: restart_rsyslog_service
     when: rsys_log_srv|default

   - name: Force rsyslog services
     meta: flush_handlers
